- name: Variables from files
  hosts: localhost
  vars_files:
    variables.yaml
  tasks: 
    - name: Variables from files
      ansible.builtin.debug:
        msg: "I am Watching {{Movie}}, Acted by {{Hero}} & Directed by {{Director}}"
